# Generated by Django 3.0.6 on 2020-06-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('date_of_birth', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=250)),
                ('no_of_publications_journal', models.CharField(max_length=250)),
                ('no_of_publications_conference', models.CharField(max_length=250)),
                ('professional_memberships', models.CharField(max_length=250)),
                ('research_interest', models.CharField(max_length=250)),
                ('faculty_id', models.CharField(max_length=250)),
            ],
        ),
    ]
