# Generated by Django 3.0.6 on 2020-06-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200610_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summery', models.CharField(max_length=250)),
                ('switches', models.TextField()),
                ('controller', models.CharField(max_length=250)),
                ('accesspoint', models.CharField(max_length=250)),
            ],
        ),
    ]
