# Generated by Django 3.0.6 on 2020-06-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_id',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
